InformationRetrieval/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include('Search.urls', namespace='Search')),
]

Search/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
    url(r'^index.html$', views.index_search, name="search"),
    url(r'^clusters/index.html$', views.index_cluster, name="cluster")
]

Search/models.py
from django.db import models

# Create your models here.

Search/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField(label='search_query', max_length=200)

Search/views.py
from django.shortcuts import render

from .forms import SearchForm

import math
import operator
import numpy


def index_search(request):
    x = 0
    post_get = 0
    context = {
        'x': x,
    }

    page = 1
    rel_fed = 0
    query = ''
    p_rel_fed = 0
    sorting = 'naive'
    hits = 0

    if 'search_query_get' in request.GET:
        query_g = request.GET['search_query_get']
        query = query_g
        post_get = 1
    if 'page' in request.GET:
        page = int(request.GET['page'])
    if 'rel_fed' in request.GET:
        rel_fed = int(request.GET['rel_fed'])
    if 'p_rel_fed' in request.GET:
        p_rel_fed = int(request.GET['p_rel_fed'])
    if 'sorting' in request.GET:
        sorting = request.GET['sorting']
    if 'hits' in request.GET:
        hits = int(request.GET['hits'])

    context['page'] = page
    context['rel_fed'] = rel_fed
    context['p_rel_fed'] = p_rel_fed
    context['sorting'] = sorting
    context['hits'] = hits

    if request.method == 'POST' or post_get == 1:
        if post_get == 0:
            query = request.POST['search_query']

        query_words = query.split(' ')
        d_id = {}
        page_rank_d_id = {}

        suggestion_string = ""
        if query != "":
            suggestion_string = bigram_spell_checker(query_words)

        for query_word in query_words:
            token_f = ""
            for token in token_document_ii:
                if query_word.lower() == token.lower():
                    token_f = token
                    break
            if token_f is not "":
                for token_i in token_document_ii[token_f]:
                    keys_value = list(token_i.keys())
                    if keys_value[0] not in d_id:
                        d_id[keys_value[0]] = token_i['TFID']
                    else:
                        d_id[keys_value[0]] += token_i['TFID']

                    if keys_value[0] not in page_rank_d_id:
                        if urls[int(keys_value[0])] in page_rank:
                            page_rank_d_id[keys_value[0]] = page_rank[urls[int(keys_value[0])-1]] * token_i['TFID']
                    else:
                        if urls[int(keys_value[0])] in page_rank:
                            page_rank_d_id[keys_value[0]] += page_rank[urls[int(keys_value[0])-1]] * token_i['TFID']

        sorted_d_id = sorted(d_id.items(), key=operator.itemgetter(1), reverse=True)
        sorted_page_rank_d_id = sorted(page_rank_d_id.items(), key=operator.itemgetter(1), reverse=True)

        documents = []
        document_titles = []

        documents_page_rank = []
        document_titles_page_rank = []

        j = 0
        for i_element in sorted_d_id:
            documents.append(urls[int(i_element[0]) - 1])
            document_titles.append(titles[urls[int(i_element[0]) - 1]])
            j += 1

        doc_hub_score = {}
        doc_authority_score = {}

        if hits == 1:
            doc_hub_score, doc_authority_score = hits_score(documents, sorted_d_id)

        j = 0
        for i_element in sorted_page_rank_d_id:
            documents_page_rank.append(urls[int(i_element[0]) - 1])
            document_titles_page_rank.append(titles[urls[int(i_element[0]) - 1]])
            j += 1

        recommended_cluster = {}
        recommended_cluster_name = ""

        if len(documents) > 0:
            for cluster in clusters:
                for cluster_url_title_pair in clusters[cluster]:
                    if documents[0] in cluster_url_title_pair:
                        recommended_cluster[cluster] = clusters[cluster]
                        recommended_cluster_name = cluster_names[cluster]
                        break
                if recommended_cluster_name != "":
                    break

        # context['documents'] = documents
        # context['document_titles'] = document_titles
        if sorting == 'page_rank':
            context['documents_titles'] = list(zip(documents_page_rank, document_titles_page_rank))
        else:
            context['documents_titles'] = list(zip(documents, document_titles))
        context['x'] = 1
        context['query'] = query
        context['suggestion_string'] = suggestion_string
        context['pager_length'] = range(1, int(math.ceil(len(documents)/10))+1)
        context['no_of_pages'] = int(math.ceil(len(documents) / 10))
        context['page'] = page
        context['list_range'] = "%d:%d" % ((page-1)*10, page*10)
        context['rel_fed'] = rel_fed
        context['p_rel_fed'] = p_rel_fed
        context['recommended_cluster'] = recommended_cluster
        context['recommended_cluster_name'] = recommended_cluster_name
        context['page_rank'] = page_rank
        """
        context['hub_score'] = hub_score
        context['authority_score'] = authority_score
        """
        context['doc_hub_score'] = doc_hub_score
        context['doc_authority_score'] = doc_authority_score
        context['sorting'] = sorting

        if rel_fed == 2 or p_rel_fed == 1:
            rel_fed_relevant_documents = []
            rel_fed_irrelevant_documents = []

            rel_fed_relevant_words = {}
            rel_fed_irrelevant_words = {}

            if rel_fed == 2:
                for document in documents:
                    if 'rel_fed_form_' + str(document) in request.POST:
                        if request.POST['rel_fed_form_'+str(document)] == '1':
                            rel_fed_relevant_documents.append(document)
                        else:
                            rel_fed_irrelevant_documents.append(document)
            if p_rel_fed == 1:
                for document in documents[:2]:
                    rel_fed_relevant_documents.append(document)

            for token in token_document_ii:
                for document in rel_fed_relevant_documents:
                    for doc_details in token_document_ii[token]:
                        if str((urls.index(document)+1)) in list(doc_details.keys()):
                            if token not in rel_fed_relevant_words:
                                rel_fed_relevant_words[token] = doc_details['TFID']
                            else:
                                rel_fed_relevant_words[token] += doc_details['TFID']
                for document in rel_fed_irrelevant_documents:
                    for doc_details in token_document_ii[token]:
                        if str((urls.index(document)+1)) in list(doc_details.keys()):
                            if token not in rel_fed_irrelevant_words:
                                rel_fed_irrelevant_words[token] = doc_details['TFID']
                            else:
                                rel_fed_irrelevant_words[token] += doc_details['TFID']
            rel_fed_relevant_words_sorted = sorted(rel_fed_relevant_words.items(), key=operator.itemgetter(1), reverse=True)

            rel_fed_irrelevant_words_sorted = sorted(rel_fed_irrelevant_words.items(), key=operator.itemgetter(1), reverse=True)

            count = 0

            rel_fed_suggestion_string = ""

            for query_word in query_words:
                if query_word in rel_fed_irrelevant_words_sorted[:5]:
                    pass
                else:
                    rel_fed_suggestion_string += query_word + " "

            for word in rel_fed_relevant_words_sorted:
                flag = 0
                for word1 in rel_fed_irrelevant_words_sorted[:5]:
                    if word[0] == word1[0]:
                        flag = 1
                        break
                if flag == 1:
                    pass
                else:
                    rel_fed_suggestion_string += word[0] + " "
                    count += 1
                if count == 5:
                    break

            context['rel_fed_suggestion_string'] = rel_fed_suggestion_string.strip()

        return render(request, 'Search/search.html', context)

    else:
        form = SearchForm()
        context['form'] = form
        return render(request, 'Search/search.html', context)


def index_cluster(request):
    context = {
        'clusters': clusters,
        'cluster_names': cluster_names,
    }
    return render(request, 'Search/clusters.html', context)

irrelevant_characters = ['`', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', '[', ']', '\\', ';', '\'', ',', '.', '/', '~', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', '{', '}', '|', ':', '\"', '<', '>', '?']


def levenshtein_distance(word_a, word_b):
    count = 0
    word_b_characters = list(word_b)
    for character in word_a:
        if character in word_b_characters:
            word_b_characters.pop(word_b_characters.index(character))
        else:
            count += 1

    return len(word_b_characters) + count


def bigram_spell_checker(query_words):
    suggestion_word_list = {}
    suggestion_string = ""
    for query_word in query_words:
        flag = 0
        suggestion_word_list_q = {}
        for token in token_document_ii:
            if query_word.lower() == token.lower():
                flag = 1
                suggestion_word_list[query_word] = query_word
                suggestion_string += query_word + " "
                break
        if flag == 0:
            for char_i in range(len(query_word)-1):
                query_word_lower = query_word.lower()
                if (query_word_lower[char_i]+query_word_lower[char_i+1]) in bigrams:
                    for token_b in bigrams[query_word_lower[char_i]+query_word_lower[char_i+1]]:
                        if token_b not in suggestion_word_list_q:
                            suggestion_word_list_q[token_b] = 1
                        else:
                            suggestion_word_list_q[token_b] += 1
            suggestion_word_list_q_sorted = sorted(suggestion_word_list_q.items(), key=operator.itemgetter(1), reverse=True)
            if len(suggestion_word_list_q_sorted) > 0:
                irrelevant_flag = 0

Search/templates/Search/clusters.html
<!DOCTYPE html>
{% load staticfiles %}
{% load index %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Clusters</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">  <!-- viewport="device screen"  width=device screen width scale =100% -->
    <!-- Available on getbootstrap CND   -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
      <script
    src="https://code.jquery.com/jquery-3.2.1.js"
    integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
    crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/cluster_style.css' %}" type="text/css">

    <script src="//storage.googleapis.com/code.getmdl.io/1.0.6/material.min.js"></script>

    <link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons" type="text/css">
    <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.teal-pink.min.css" type="text/css">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
    <link rel="shortcut icon" type="image/png" href="{{STATIC_URL}}/favicon.ico"/>
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
</head>
<body>

<div class="container-fluid" id="outer_row_div" >
    <div class="row" id="row_div" >
        <div class="col-md-12" id="cluster_div_nav">
            <span id="page_title" >Clusters</span>
            <i id="back_icon" class="material-icons md-36" onclick="location.href = `{% url 'Search:search' %}`" >arrow_back</i>
        </div>

        <div class="col-md-12" id="cluster_area">
            {% for cluster in clusters %}
            <div class="col-md-3 card card1 cluster " id="cluster_{{ i }}">
                <div class="cluster_title">
                    <span>Cluster {{ cluster|inc:1 }}({{ cluster_names|list_index:cluster }})</span>
                    <span class="cluster_pages"><span class="pages" >Page(s): {{ clusters|list_index:cluster|length }}</span></span>
                </div>

                <div class="cluster_urls" >
                    <ul>
                        {% for j in clusters|list_index:cluster %}
                        <li><span class="cluster_url" ><a class="cluster_url_a" href="{{ j.0 }}" >{{ j.1 }}</a></span><br></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <!--{% if cluster == 2 or cluster == 5 or cluster == 8 %}
            <div class="clearfix" ></div>
            {% endif %}-->
            {% endfor %}
        </div>

    </div>
</div>

<script>
    $(document).ready(function () {
      var container = document.querySelector('#cluster_area');
      var msnry = new Masonry(container, {
                    itemSelector: '.cluster'
                  });
    });
</script>
</body>
</html>

Search/templates/Search/search.html
<!DOCTYPE html>
{% load staticfiles %}
{% load index %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">  <!-- viewport="device screen"  width=device screen width scale =100% -->
    <!-- Available on getbootstrap CND   -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
      <script
    src="https://code.jquery.com/jquery-3.2.1.js"
    integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
    crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/search_style.css' %}" type="text/css">

    <script src="//storage.googleapis.com/code.getmdl.io/1.0.6/material.min.js"></script>

    <link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons" type="text/css">
    <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.teal-pink.min.css" type="text/css">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
    <link rel="shortcut icon" type="image/png" href="{{STATIC_URL}}/favicon.ico"/>

</head>
<body>

<div id="loading">
    <span id="loading_text" >Loading...</span>
</div>

<div class="container-fluid" id="outer_row_div" >
    <div class="row" id="row_div" >


        <div class="col-md-12" id="search_bar_div_nav" >
            <form action="{% url 'Search:search' %}" method="POST">
                {% csrf_token %}
                {{ form.errors }}
                {{ form.non_field_errors }}
                <div id="search_bar_div" class="card card1 col-md-8">
                    <input type="text" name="search_query" placeholder="Search here" id="search_query_input" class="col-md-11" value="{{ query }}" >
                    <button type="submit" id="search_button" class="col-md-1"><img src="{% static 'Search/search.png' %}" alt="Search"/></button>
                </div>
            </form>
            <div class="col-md-12" id="tab_div">
                <button class="tab_button btn {% if sorting == 'naive' %} tab_active {% endif %}" onclick="location.href= `{% url 'Search:search' %}?sorting=naive&search_query_get={{ query }}`" >Naive</button>
                <button class="tab_button btn {% if sorting == 'page_rank' %} tab_active {% endif %}" onclick="location.href= `{% url 'Search:search' %}?sorting=page_rank&search_query_get={{ query }}`" >Page Rank</button>
            </div>
        </div>

        <form action="{% url 'Search:search' %}?search_query_get={{ query }}&page={{ page }}&rel_fed=2" method="POST">
            {% csrf_token %}

            <div id="result_area" class="col-md-8">
                <!--<div class="document_link_div col-md-8 card card2">
                    <h6 class="document_title"><a href="#" class="document_link_a">Page Title</a></h6>
                    <cite class="document_link_cite">link</cite>
                    <p class="document_body" >Document Body</p>
                </div>-->

                {% if x == 0 %}
                <span> Search something</span>
                {% else %}

                <p id="results_number" class="col-md-12"> {% if documents_titles|length != 0 %} {% if no_of_pages == 1 %} {% if documents_titles|length == 1 %} 1 result found. {% else %} {{ documents_titles|length }} results found. {% endif %} {% else %} About {{ documents_titles|length }} results. {% endif %} {% else %} No results found. {% endif %} </p>

                <p id="suggestion_div"
                   class="col-md-12" {% if suggestion_string == query %} hidden {% endif %} > {% if suggestion_string != query %} Did you mean <a href="{% url 'Search:search' %}?search_query_get={{ suggestion_string }}" ><em>{{ suggestion_string }}</em></a>? {% endif %} </p>

                <p id="rel_fed_suggestion_div" class="col-md-12" {% if rel_fed != 2 and p_rel_fed != 1 %} hidden {% endif %} > {% if rel_fed == 2 %} Based on your feedback the query <a href="{% url 'Search:search' %}?search_query_get={{ rel_fed_suggestion_string }}" ><em>{{ rel_fed_suggestion_string }}</em></a> might give more relevant results. {% elif p_rel_fed == 1 %} Based on pseudo relevance feedback the query <a href="{% url 'Search:search' %}?search_query_get={{ rel_fed_suggestion_string }}" ><em>{{ rel_fed_suggestion_string }}</em></a> might give more relevant results. {% endif %}</p>

                {% for document_url,document_title in documents_titles|slice:list_range %}
                <div class="document_link_div col-md-12 card card2" ondblclick="location.href='{{ document_url }}'" >
                    <div class="col-md-10" >
                        <h6 class="document_title"><a href="{{ document_url }}" class="document_link_a">{{ document_title }}</a></h6>
                        {% if hits == 1 %}
                        <span class="hub_authority" >Type: {% if doc_hub_score|rank_score:document_url >= doc_authority_score|rank_score:document_url %} Hub {% else %} Authority {% endif %}</span>
                        {% endif %}
                        <cite class="document_link_cite">{{ document_url }}</cite>
                        <cite class="page_rank" ><b class="bold" >Page Rank:</b> {{ page_rank|rank_score:document_url }} </cite>
                        {% if hits == 1 %}
                        <span> | </span>
                        <cite class="hub_score" ><b class="bold" > Hub Score:</b> {{ doc_hub_score|rank_score:document_url }} </cite><span> | </span>
                        <cite class="authority_score" ><b class="bold" > Authority Score:</b> {{ doc_authority_score|rank_score:document_url }}</cite>
                        {% endif %}
                    </div>
                    {% if rel_fed == 1 %}
                    <div class="col-md-2 rel_fed_form_div" >
                        <div id="rel_radio" class="rel_ir" >
                            <span class="rel_text" >Relevant</span>
                            <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect ir_relevant" for="relevant_{{ document_url }}">
                                <input type="radio" id="relevant_{{ document_url }}" class="mdl-radio__button" name="rel_fed_form_{{ document_url }}" value="1">
                            </label>
                        </div>
                        <div id="irrel_radio" class="rel_ir" >
                            <span class="rel_text" >Irrelevant</span>
                            <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect ir_relevant" for="irrelevant_{{ document_url }}">
                                <input type="radio" id="irrelevant_{{ document_url }}" class="mdl-radio__button" name="rel_fed_form_{{ document_url }}" value="0">
                            </label>
                        </div>
                    </div>
                    {% endif %}
                </div>
                {% endfor %}
                {% endif %}

            </div>

            {% if sorting != 'page_rank' %}

            <div id="tools_area" class="col-md-3 card card2">
                <span id="tools_area_title" >
                    Tools
                </span>
                <div class="flip-container col-md-6" id="flip-container" >
                    <div class="flipper">
                        <div id="relevance_feedback_div" class="front" onclick=" {% if documents_titles|length != 0 %} location.href= `{% url 'Search:search' %}?rel_fed=1&page={{ page }}&search_query_get={{ query }}` {% else %} location.href= `{% url 'Search:search' %}` {% endif %}">
                            <i id="rel_fed_icon" class="material-icons teal900 md-48">assignment</i>
                            <span class="icon_desc" >Relevance Feedback</span>
                        </div>

                        <div id="rel_fed_submit" class="back" >
                            <button class="btn buttn" type="submit">Submit</button>
                            <button class="btn buttn" type="button" onclick="location.href=`{% url 'Search:search' %}?page=1&search_query_get={{ query }}`">Cancel</button>
                        </div>

                    </div>
                </div>
                <div id="pseudo_relevance_feedback_div" class="col-md-6" onclick="{% if documents_titles|length != 0 %} location.href= `{% url 'Search:search' %}?p_rel_fed=1&page={{ page }}&search_query_get={{ query }}` {% else %} location.href= `{% url 'Search:search' %}` {% endif %}">
                    <i id="pseudo_rel_fed_icon" class="material-icons teal900 md-48">assignment_turned_in</i>
                    <span class="icon_desc" >P - Relevance Feedback</span>
                </div>
                <div id="topic_modelling_div" class="col-md-6" onclick="{% if documents_titles|length != 0 %} location.href= `{% url 'Search:search' %}?hits=1&page={{ page }}&search_query_get={{ query }}` {% else %} location.href= `{% url 'Search:search' %}` {% endif %}">
                    <i id="topic_modelling_icon" class="material-icons teal900 md-48">flare</i>
                    <span class="icon_desc" >HITS Analysis</span>
                </div>
                <div id="clustering_div" class="col-md-6" onclick="location.href= `{% url 'Search:cluster' %}`">
                    <i id="clustering_icon" class="material-icons teal900 md-48">group_work</i>
                    <span class="icon_desc">Clusters</span>
                </div>
            </div>

            {% endif %}

            {% if recommended_cluster|length != 0 %}
            <div id="recommended_cluster_area" class="col-md-3 card card2">
                <span id="cluster_area_title" >You may find these pages useful.</span><br>
                {% for cluster in recommended_cluster %}
                <div class="col-md-12 card card1" id="cluster">
                    <div class="cluster_title">

                        <span>Cluster {{cluster|inc:1}}({{recommended_cluster_name}})</span>
                        <span class="cluster_pages" ><span class="pages" >Page(s): {{recommended_cluster|list_index:cluster|length}}</span></span>
                    </div>

                    <div class="cluster_urls" >
                        <ul>
                            {% for j in recommended_cluster|list_index:cluster %}
                            <li><span class="cluster_url" ><a class="cluster_url_a" href="{{ j.0 }}" >{{ j.1 }}</a></span><br></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endif %}

        </form>

        <div id="pager_div" class="col-md-12">
            {% if rel_fed == 0 %}

            {% for i in pager_length %}
            <a class="pager" href="{% url 'Search:search' %}?page={{ i }}&search_query_get={{ query }}&sorting={{ sorting }}" >{{ i }}</a>
            {% endfor %}

            {% endif %}
        </div>


        <div id="bottom_bar" class="col-md-12 footer">



        </div>

    </div>
</div>

{% if rel_fed == 1 %}
<script>
    $(document).ready(function() {
    $("#flip-container").toggleClass("flip");
    });
</script>
{% endif %}

<script>
    function onReady(callback) {
        var intervalID = window.setInterval(checkReady, 10);
        console.log('asfdsjafbas');
        function checkReady() {
            if (document.getElementsByTagName('body')[0] !== undefined) {
                window.clearInterval(intervalID);
                callback.call(this);
            }
        }
    }

    function show(id, value) {
        document.getElementById(id).style.display = value ? 'block' : 'none';
    }

    onReady(function () {
        show('outer_row_div', true);
        show('loading', false);
    });
</script>

</body>
</html>